apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      targetPort: 5432
      port: 5432
  type: NodePort
  selector:
    app: postgres