apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-pv-claim
  labels:
    app: postgress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1g