apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgress-pv-volume
  labels:
    type: local
    app: postgress
spec:
  storageClassName: manual
  capacity:
    storage: 5g
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
