version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend-gateway
      - backend-analytics
      - backend-resource
      - connector

  backend-analytics:
    build:
      context: ./backend/analytics
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  backend-resource:
    build:
      context: ./backend/resource
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  backend-gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  connector:
    build:
      context: ./connector
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
