version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend-gateway
      - backend-analytics
      - backend-resource
      - connector

  backend-analytics:
    build:
      context: ./backend/analytics
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  backend-resource:
    build:
      context: ./backend/resource
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  backend-gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  connector:
    build:
      context: ./connector
      dockerfile: Dockerfile
    ports:
      - "8003:8003"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pswd"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: