version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    container_name: backend
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

  connector:
    container_name: connector
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

  web:
    container_name: web
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data: