version: "3.9"

services:

  app-db:
    container_name: app-db
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  app-backend:
    container_name: app-backend
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

  app-connector:
    container_name: app-connector
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

  app-web:
    container_name: app-web

volumes:
  testdb-data: