jiraUrl: https://issues.apache.org/jira
threadCount: 10
issueInOneRequest: 100
maxTimeSleep: 8000
minTimeSleep: 50

database:
 hostDB: localhost
 portDB: 5432
 nameDB: testdb
 passwordDB: pgpwd
 userDB: pguser

apiServer:
 hostServer: localhost
 portServer: 8080
 apiPref: /api/v1

resource:
 resourceHost: localhost
 resourcePort: 8001
 resourcePref: /resource

analytics:
 analyticHost: localhost
 analyticPort: 8002
 analyticPref: /graph

connector:
 connectorHost: localhost
 connectorPort: 8003
 connectorPref: /connector