jiraUrl: http://issues.apache.org/jira
threadCount: 10
issueInOneRequest: 100
maxTimeSleep: 10000
minTimeSleep: 50

hostDB: localhost
portDB: 5432 
databaseName: testdb
passwordDB: pgpwd
userDb: pguser

hostServer: localhost
portServer: 8003