jiraUrl: https://issues.apache.org/jira
threadCount: 10
issueInOneRequest: 100
maxTimeSleep: 8000
minTimeSleep: 50

hostDB: localhost
portDB: 5432 
NameDB: testdb
passwordDB: pgpwd
userDB: pguser

hostServer: localhost
portServer: 8080

apiPref: /api/v1